In [1]:
import tensorflow as tf
import numpy as np
 
def dynamic_rnn(rnn_type='lstm'):
    # 创建输入数据,3代表batch size,6代表输入序列的最大步长(max time),4代表每个序列的维度
    X = np.random.randn(3, 6, 4)
    
    # 第二个输入的实际长度为4
    X[1, 4:] = 0
    
#     print(X)
 
    #记录三个输入的实际步长
    X_lengths = [6, 4, 6]
 
    rnn_hidden_size = 5
    if rnn_type == 'lstm':
        cell = tf.contrib.rnn.BasicLSTMCell(num_units=rnn_hidden_size, state_is_tuple=True)
    else:
        cell = tf.contrib.rnn.GRUCell(num_units=rnn_hidden_size)
 
    outputs, last_states = tf.nn.dynamic_rnn(
        cell=cell,
        dtype=tf.float64,
        sequence_length=X_lengths,
        inputs=X)
 
    with tf.Session() as session:
        session.run(tf.global_variables_initializer())
        o1, s1 = session.run([outputs, last_states])
        print(np.shape(o1))
        print(o1)
        print(np.shape(s1))
        print(s1)
 
if __name__ == '__main__':
    dynamic_rnn(rnn_type='lstm2')

(3, 6, 5)
[[[ 0.02583007 -0.16254963  0.03231111  0.13380627  0.09984674]
  [ 0.31533677 -0.28856638  0.28676979  0.66834642  0.20629172]
  [ 0.2168452  -0.31239146  0.3448263   0.58530746  0.28613652]
  [ 0.16463892 -0.13676556  0.2248685   0.4501862   0.21060677]
  [ 0.39875529 -0.07775414  0.15274406  0.70250861  0.22492563]
  [ 0.27753744 -0.25435448  0.10548806  0.70172589  0.31703284]]

 [[-0.05804742 -0.05726003  0.00253014  0.07414394  0.3347976 ]
  [ 0.06043956  0.13199878 -0.12044179  0.05901967  0.17048757]
  [ 0.3937168  -0.02183664  0.04266898  0.74316619  0.28750419]
  [ 0.33702695  0.09514529 -0.05427569  0.58400851  0.2129373 ]
  [ 0.          0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.          0.        ]]

 [[ 0.43695148 -0.08954564  0.26569339  0.57627956  0.05761864]
  [ 0.48154119 -0.07834778  0.01570002  0.52587216 -0.00188863]
  [ 0.59268014  0.16710224 -0.09626333  0.80345016  0.19697336]
  [ 0.71011909  0.07648784